specs:
  - name: tracey
    prefix: r
    source_url: "https://github.com/bearcove/tracey"
    include:
      - "docs/spec/**/*.md"
    impls:
      - name: main
        include:
          - "crates/**/*.rs"
          - "crates/**/*.ts"
          - "crates/**/*.tsx"
          - "crates/**/*.css"
          - "tracey-zed/src/**/*.rs"
          - "../marq/**/*.rs"
        exclude:
          - "target/**"
          - "../marq/target/**"
